// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcfnrsvlwfpnlevaanzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZm5yc3Zsd2ZwbmxldmFhbnpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA3NTc4NjgsImV4cCI6MjA3NjMzMzg2OH0.YY6mRZukd2rj4yhCX90kuSGQUsV6vERQr-r6h7m9PFM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});